url: https://gainbound.net
host: gainbound.net
siteType: NexusPHP
icon: data:image/png;base64,AAABAAEAICAAAAEAIACoEAAAFgAAACgAAAAgAAAAQAAAAAEAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AOFvIgDhbyIA4W8iAOFvIgDhbyIA4W8iAOFvIhrhbyJ54W8ik+FvImThbyIx4W8iDuFvIgDhbyIA4W8iAOFvIgD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A4XAiAOFwIgDhcCIA4XAiAOFwIgDhcCIY4G4h195pH//daB7/3mkf/95qH/7fbCDk4G4huuFwIoXhcCJS4XAiI+FwIgb///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wDicSQA4nEkAOJxJADicSQA4nEkAOJxJHnfayH/3Wgg/91oIP/daCD/3Wgg/91pIP/eaSH/3moh/99rIf/fbCL64G4j1+FwI6ricSR14nEkQOJxJBj///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AOJzJQDicyUA4nMlAOJzJQDicyUA+uXX6//////////////////////////////////////eayL/3msi/95rIv/ebCL/32wj/99tI//gbiP/4G8k8OFxJMv99O/y//////ro25nicyUM////AP///wD///8A////AP///wD///8A43UnAON1JwDjdScA43UnAON1Jwfzx6jw99vJ///////////////////////55Nf/99vJ/99uJf/fbiX/324l/99uJf/fbiX/324l/99uJf/fbiX/77eS////////////8LmU/uFyJuTicye743UnieN1J0rjdScG////AP///wDkdykA5HcpAOR3KQDkdykA5HcpLOJ0KPzgcij/7rCG////////////8LmU/+ByKP/gcij/4HIo/+ByKP/gcij/4HIo/+ByKP/gcij/4HIo/+SEQ//////////////////wuZT/4HIo/+BzKP/hcyj/4nQo/+N3KaTkdykB////AOR5KwDkeSsA5HkrAOR5KwDkeStY4nYr/+F1K//jfjj////////////pmGD/4XUr/+F1K//hdSv/4XUr/+F1K//hdSv/4XUr/+F1K//hdSv/+N3L//////////////////C6lf/hdSv/4XUr/+F1K//hdSv/4ncr/+R5K1T///8A5XssAOV7LADleywA5XssAOV7LI3jei7/4nku/+J5Lv///////////+mbYv/ieS7/4nku/+J5Lv/ieS7/4nku/+J5Lv/ieS7/4nku/+ujcP//////////////////////8byX/+J5Lv/ieS7/4nku/+J5Lv/jei7/5XssdP///wDlfS4A5X0uAOV9LgDlfS4A5X0vwuN8Mf/jfDH/43wx////////////6p1l/+N8Mf/jfDH/43wx/+N8Mf/jfDH/43wx/+N8Mf/lhD7//O/m///////////////////////xvpj/43wx/+N8Mf/jfDH/43wx/+R8MP/lfS5P////AOaAMADmgDAA5oAwAOaAMBPlgDLm5IA0/+SANP/kgDT////////////roGf/5IA0/+SANP/kgDT/5IA0/+SANP/kgDT/5IA0//PIp//////////////////9+PP///////LAmv/kgDT/5IA0/+SANP/kgDT/5YAy9uaAMB////8A54IyAOeCMgDngjIA54IyN+aDNv/lhDj/5YQ4/+WEOP///////////+yjav/lhDj/5YQ4/+WEOP/lhDj/5YQ4/+WEOP/qm13/////////////////99nB//nhzv//////8sKc/+WEOP/lhDj/5YQ4/+WEN//mgzTQ54IyAv///wDnhDQA54Q0AOeENADnhDRs5oc5/+aIO//miDv/5og7////////////7KZs/+aIO//miDv/5og7/+aIO//miDv/5og7//niz/////////////748//pl1T/+eLP///////zxJ3/5og7/+aIO//miDv/5oc6/+eFNaX///8A////AOiHNgDohzYA6Ic2AOiHN57niz3/54w+/+eMPv/njD7////////////tqW7/54w+/+eMPv/njD7/54w+/+eMPv/wt4f/////////////////88af/+eMPv/548////////PGn//njD7/54w+/+eMPv/nizz/6Ic2bv///wD///8A6Ik4AOiJOADoiTgA6Is7z+iOQf/oj0L/6I9C/+iPQv///////////+6rcf/oj0L/6I9C/+iPQv/oj0L/6ZZO//749P////////////zx6P/oj0L/6I9C//nj0P//////9Meh/+iPQv/oj0L/6I9C/+iMPv/oiTg6////AP///wDpizoA6Ys6AOmLOh7pj0D06ZNF/+mTRf/pk0X/6ZNF////////////7650/+mTRf/pk0X/6ZNF/+mTRf/317r/////////////////7650/+mTRf/pk0X/+uTR///////0yaL/6ZNF/+mTRf/pk0T/6Y8/7OmLOhf///8A////AOqNPADqjTwA6o08SOqTRP/qlkj/6pZI/+qWSP/qlkj////////////vsHb/6pZI/+qWSP/qlkj/77B2//////////////////fYu//qlkj/6pZI/+qWSP/65dL///////XLpP/qlkj/6pZI/+qVR//qjz/G////AP///wD///8A6o8+AOqPPgDqjz5665dI/+uaS//rmkv/65pL/+uaS/////////////CzeP/rmkv/65pL/+uaS//77N7////////////++fT/7KBW/+uaS//rmkv/65pL//rm0///////9c2l/+uaS//rmkv/65hI/+qQP5D///8A////AP///wDrkUAA65FAAOuTQrLsm0z/7J1O/+ydTv/snU7/7J1O////////////8bZ6/+ydTv/snU7/9Mic//////////////////TInP/snU7/7J1O/+ydTv/snU7/+ufT///////2zqf/7J1O/+ydTv/smUn/65FAYP///wD///8A////AOuSQQDrkkEJ7JdH2u2eT//tn1D/7Z9Q/+2fUP/tn1D////////////yt3z/7Z9Q/++rZv/++fX////////////87d//7Z9Q/+2fUP/tn1D/7Z9Q/+2fUP/759T///////bPqP/tn1D/7Z9Q/+yZSf/rkkEt////AP///wD///8A7JRDAOyUQyjtnEz87qJT/+6iU//uolP/7qJT/+6iU/////////////K5fv/uolP/+uLK//////////////////K5fv/uolP/7qJT/+6iU//uolP/7qJT//vo1f//////99Gp/+6iU//uoVL/7ZlJ3uyUQwv///8A////AP///wDtlkQP7ZZEWe6gUP/vpVb/76VW/++lVv/vpVb/76VW////////////87yA//O8gP/////////////////42LX/76VW/++lVv/vpVb/76VW/++lVv/vpVb/++nV///////30qv/76VW/++jU//tmUi1////AP///wD///8A////AO2YRzTumkqM76VW//CpW//wqVv/8Klb//CpW//wqVv////////////0v4T//fXr/////////////vr1//GuZf/wqVv/8Klb//CpW//wqVv/8Klb//CpW//76tb///////jUrf/wqVv/76VW/+2YSIH///8A////AP///wD///8A7ZpKT+6eTqzvqFv/8Kxf//CsX//wrF//8Kxf//CsX/////////////vq1//////////////////2y5v/8Kxf//CsX//wrF//8Kxf//CsX//wrF//8Kxf//vq1///////++rX//CsX//vplj/7ZpKSv///wD///8A////AP///wDunEwf7pxMbPCnWv/xrmL/8a9j//GvY//xr2P/9cOK/////////////////////////////OvY//GvY//xr2P/8a9j//GvY//xr2P/8a9j//GvY//0voD//vr2///////++vb/87h2/++mWPXunEwj////AP///wD///8A////AO6dTgDunU4B7p1OlO+mWfzwql7/+Nu6//zw4v/////////////////////////////////0wIP/8bFm//GxZv/xsWb/8bFm//GxZv/2zqD//PHj///////////////////////++vb//Ovb9f/9/DH///8A////AP///wD///8A7p5QAO6eUADunlAA7p5QJO6eUFP64szM/O3f7vvr2fn76tf/++rY//vr2f/869n/+Ni0//Gyaf/xsmn/8bJp//Gyaf/xsmn/8bJp//bPof/87Nr//Oza//zs2v/87Nr//Oza//vr2f/87+Ho////MP///wD///8A////AP///wDun1IA7p9SAO6fUgDun1IA7p9SAO6fUgDun1IA7p9SDe6fUjTun1Jm76FUme+lWszwqV7x8axi//GuZf/xsGj/8rJq//K0a//ytGz/8rRs//K0bP/ytGz/8rRs//K0bP/ytGz/8a5k/+6fUnL///8A////AP///wD///8A////AO6fUwDun1MA7p9TAO6fUwDun1MA7p9TAO6fUwDun1MA7p9TAO6fUwDun1MA7p9TAO6fUxnun1NC7p9Td++jWKzwp13Y8Kth+/GuZf/xsGj/8rJq//K0bP/ytW7/8rVu//K0bP/wqmD+7p9TMv///wD///8A////AP///wD///8A7qBUAO6gVADuoFQA7qBUAO6gVADuoFQA7qBUAO6gVADuoFQA7qBUAO6gVADuoFQA7qBUAO6gVADuoFQA7qBUAO6gVAbuoFQl7qBUVO+hVYfvpVu88Klg5vCtZP/xrmb/8Kph/u6gVIL///8A////AP///wD///8A////AP///wDuoFQA7qBUAO6gVADuoFQA7qBUAO6gVADuoFQA7qBUAO6gVADuoFQA7qBUAO6gVADuoFQA7qBUAO6gVADuoFQA////AP///wD///8A////AP///wDuoFQO7qBUNe6gVFnuoFQu////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A////AP///wD///8A//////9////8A////AA///gAAH/4AAAP+AAAA/gAAAPwAAAD8AAAA/AAAAPwAAAD8AAAA+AAAAfgAAAH4AAAB+AAAAfgAAAHwAAAD8AAAA/AAAAPwAAAD4AAAA+AAAAfwAAAH8AAAB/4AAAf/8AAP//+AD///+A///////////8=
asSource: true
asTarget: true
seedDomSelector: '#top~table:first>tbody>tr:nth-child(6)'
uploadPath: /upload.php
search:
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
  result:
    list: .torrents>tbody>tr
    url: .torrentname td a[href*="details.php?id="]
    name: .torrentname td a[href*="details.php?id="]
    size: td:nth-child(5)
name:
  selector: '#name'
subtitle:
  selector: input[name="small_descr"]
description:
  selector: textarea[name="descr"]
imdb:
  selector: input[name="url"][type="text"]
anonymous:
  selector: input[name="uplver"]
tags:
  chinese_audio: 'input[name="tags[]"][value="5"]'
  diy: 'input[name="tags[]"][value="2"]'
  chinese_subtitle: 'input[name="tags[]"][value="6"]'
  cantonese_audio: 'input[name="tags[]"][value="4"]'
category:
  selector: '#browsecat'
  map:
    movie: '401'
    tv: '410'
    tvPack: '410'
    documentary: '404'
    concert: '406'
videoCodec:
  selector: select[name="codec_sel"]
  map:
    h264: '1'
    hevc: '6'
    h265: '6'
    x264: '1'
    x265: '6'
    mpeg2: '4'
    mpeg4: '1'
    vc1: '2'
    xvid: '3'
videoType:
  selector: select[name="medium_sel"]
  map:
    uhdbluray: '1'
    bluray: '1'
    remux: '3'
    encode: '7'
    web: '4'
    hdtv: '5'
    dvd: '6'
resolution:
  selector: select[name="standard_sel"]
  map:
    1080p: '1'
    1080i: '1'
    720p: '6'
    480p: '4'
area:
  selector: select[name="processing_sel"]
  map:
    US: '4'
    EU: '4'
    HK: '3'
    TW: '3'
    JP: '5'
    KR: '5'
    OT: '6'
team:
  selector: select[name="team_sel"]
  map:
    dgb: '3'
    dgbweb: '7'
