url: 'http://www.hd.ai'
host: hd.ai
siteType: NexusPHP
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAACLlBMVEUnJyciIiInJycnJycnJycnJycnJycoKCgnJycnJycnJycnJycmJiYmJiYmJiYlJSUmJiYkJCQjIyMjIyMjIyMjIyMiIiIiIiIiIiIiIiIhISEiIiIhISEhISEhISEhHx8eQFUaercdUnQhIiIhISEhISEoKCgnJycmJiYlJSUyMjJAQEAkJCQ/Pz+Hh4fCwcHh4OBSUlKtra1ubWxlb3PP298+Pj7Nzc2Zm50cTF8Wg61zwd0WhK4cTmKZnJ2NjY38+/q0y9Mpn8whpdia0+ib0+gpn820y9UzMzO4t7eYoaWGwNar2eqt2OjA4OvD4eyr2Oir2OmGwdiYo6dDQ0OBf38hTV8WlsiHyOHR5e2Yz+OXz+TO5OwWlMYiQU6Bf34jIyNDQkJ/i5AccpYWlMiGxt/J4uqTy+GXzeLP5OsXksUiQU8zMjK0vMCTrLeHvdO12Oat1OS92+e72ua11+Wx1uWFvtWWoqe3trYiJiiKmKD08vG8z9gymMgilcuPxd2Zyt8ll8wslsexydT18/IjIyIhKC07U1/KycmdoqQbUGoUe61erNBosdMUe64ZUGuPlJc9PT0hISEiIiIjIiIiKSwcUWtTWV2sq6tkZGRQYGi0xs69zdRVZGxeXl6lpaVTU1MeWHccUGyFhYW5uLjY19bY19e6ubmEhIQjISEhNkIbdKQePlAiISBBQUEdVXQbc6UhMjwhIB8gICAhISAhKzEbbJwcZ5MhKjD///8cBd9jAAAAJnRSTlMAAA9wx+bs7Q6V+fjF5ezt7e3t7OXGcPgOlfkPcMfm7O3t7e3t7NLV0KEAAAABYktHRLk6uBZgAAAAB3RJTUUH5QQKBykeq2bSOAAAAXFJREFUGNNVi2VbAkEURkexAywMRGydWQdbbMHuxq6xu7u7exe7uzt/nrvKF8+n957nHgA0eVraOrpqdLS1eJoA6OkbuP3DQF8P8Azd/4BQPQx5wOh3IER5eFAI/R5GwJh7wlJPL29vL08p5qQx4EMIsY+vn39AgL+frw9mTz4QIIhlgUHBIaGhYeERgTIMkQCYQITlisio6JjY6Lh4hRwjaMLJhMSk5JTUtPSMzKzsxAROChBW5uTm5RcUFhXnl5SWKTGbCxApr6isqq6prauvbmgsUxJWmmLc1NzS2tbe0dnV3dPbR2Fsysn+gcGh4ZHRsfGJySk54aQZmZ6ZnZtfWFxaXlldm1unCTED5oxqY3Nre2d3b//g8OiYZhjGHFgwKtXJqfTs/OLy6lpKM4QwFkBIyM3t3f0D9fhIMWzLIgSWVmzw9Pzy+vbGpSxWlsDaRkS/f3x+fdNqRDbWQMNWbCexd3B0cnZhcZXYiW01fgC8EXLoIVrAZQAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMS0wNC0xMFQwNzo0MTozMCswMDowMNmd3ZQAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjEtMDQtMTBUMDc6NDE6MzArMDA6MDCowGUoAAAAAElFTkSuQmCC
asSource: true
asTarget: true
uploadPath: /Torrents.upload
seedDomSelector: '#top~table:first>tbody>tr:nth-child(3)'
search:
  path: /Torrents.index
  imdbOptionKey: '9'
  nameOptionKey: '1'
  params:
    name: '{name}'
    search_area: '{optionKey}'
    imdb: '{imdb}'
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
poster: 'input[name="poster"]'
imdb:
  selector: 'input[name="url"][type="text"]'
mediaInfo:
  selector: 'textarea[name="nfo"]'
screenshots:
  selector: 'textarea[name="screenshot"]'
tags:
  chinese_audio: 'input[type="checkbox"][name="tag[cn]"]'
  chinese_subtitle: 'input[type="checkbox"][name="tag[zz]"]'
category:
  selector: 'select[name="type"]'
  map:
    movie: '1'
    tv: '2'
    tvPack: '2'
    documentary: '4'
    concert: '6'
    sport: '7'
    cartoon: '5'
    variety: '3'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '2'
    hevc: '1'
    x264: '2'
    x265: '1'
    h265: '1'
    mpeg2: '5'
    mpeg4: '2'
    vc1: '3'
    xvid: '4'
    dvd: '5'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '10'
    ac3: '11'
    dd: '11'
    dd+: '11'
    flac: '7'
    dts: '5'
    truehd: '4'
    lpcm: '6'
    dtshdma: '2'
    atmos: '3'
    dtsx: '1'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '1'
    bluray: '2'
    remux: '3'
    encode: '5'
    web: '4'
    hdtv: '6'
    dvd: '7'
    dvdrip: '10'
    other: '0'
    cd: '8'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    4320p: '1'
    2160p: '2'
    1080p: '3'
    1080i: '4'
    720p: '5'
    576p: '6'
    480p: '6'
area:
  selector: 'select[name="source_sel"]'
  map:
    CN: '1'
    US: '2'
    EU: '2'
    HK: '3'
    TW: '3'
    JP: '4'
    KR: '5'
    OT: '6'
team:
  selector: 'select[name="team_sel"]'
  map:
    other: '1'
    ao: '20'
    beitai: '18'
    beyondhd: '19'
    beast: '23'
    chd: '2'
    chdbits: '3'
    cmct: '4'
    frds: '5'
    fltth: '17'
    hdai: '6'
    hdchina: '7'
    hdhome: '8'
    hdsky: '9'
    lemonhd: '28'
    leaguehd: '29'
    mteam: '10'
    nypt: '24'
    ngb: '26'
    ourtv: '11'
    ourbits: '12'
    pter: '13'
    pthome: '14'
    putao: '22'
    strife: '21'
    tjupt: '15'
    ttg: '16'
    tlf: '30'
    u2: '31'
    wiki: '25'
