url: 'https://www.hddolby.com'
host: hddolby.com
siteType: NexusPHP
icon: '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="11px" height="11px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">  <image id="image0" width="20" height="20" x="0" y="0"    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAAAAACo4kLRAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQflBAoGHTIjVicbAAABTUlEQVQY01WOvy9DURzFz/feW0/1pY2gogaLX4lBJBZCqiKxITGYTGIx+wOsRpbGarEwV0SExCTR+LU0GoIYMLw8vFfv1b1fgz6p73DyzUnOOR/SBEL9MVhR+Kz/mdTRpOhhwSUYFgAMJLhhK6sQ3qUWrcfDewDpqR65U64AfG2POlw9HgS69gI287LAAgCYZXY1TitzMcMAIKLJsf6OKcG/IKo2iea0bo7gRERS8fyv6P+Ll0pPV/UmCRIv+bcgXyaiWid9XNgP2wXgdGm5jxwCwDdtDclUQiqllIwnU1Zin4mdg5BBYOBX5USGjPa0HXv/Tn3H6FM3sRUoqehpo7Nx4ER0u7nkpp3xx89m2wVcf+ZyNzN9dO16TuOrWA9bWACsWTATf/jc6g5/5hTLtaB42zN5Xhqxi6bi9Q59jcaJDLORVNUWNJGRxCD8AK0whyYuCRA4AAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIxLTA0LTEwVDA2OjI5OjUwKzAwOjAwOQaHIQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMS0wNC0xMFQwNjoyOTo1MCswMDowMEhbP50AAAAASUVORK5CYII=" /></svg>'
asSource: true
asTarget: true
seedDomSelector: '#top~table:first>tbody>tr:nth-child(3)'
uploadPath: /upload.php
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
imdb:
  selector: 'input[name="url"][type="text"]'
douban:
  selector: 'input[name="douban_id"]'
tags: 
  chineseAudio: '#tag_gy'
  DIY: '#tag_diy'
  chineseSubtitle: '#tag_zz'
  cantoneseAudio: '#tag_yy'
  HDR: '#tag_hdr10'
  HDR10+: '#tag_hdrm'
  DolbyVision: '#tag_db'
anonymous: 
  selector: 'input[name="uplver"]'
category:
  selector: '#browsecat'
  map:
    movie: '401'
    tv: '402'
    tvPack: '402'
    documentary: '404'
    concert: '406'
    sport: '407'
    cartoon: '405'
    variety: '403'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '1'
    x264: '3'
    hevc: '2'
    x265: '4'
    h265: '2'
    mpeg2: '6'
    mpeg4: '0'
    vc1: '5'
    xvid: '0'
    dvd: '0'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '1'
    bluray: '2'
    remux: '3'
    encode: '10'
    web: '6'
    hdtv: '5'
    dvd: '8'
    dvdrip: '8'
    other: '0'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    2160p: '1'
    1080p: '2'
    1080i: '3'
    720p: '4'
    576p: '5'
    480p: '5'
team: 
  selector: 'select[name="team_sel"]'
  map:
    dream: '1'
    hdo: '9'
    dbtv: '10'
    nazorip: '12'
    mteam: '2'
    frds: '7'
    wiki: '4'
    beast: '11'
    chd: '5'
    cmct: '6'
    pthome: '3'
    other: '8'