url: 'https://hdhome.org'
host: hdhome.org
siteType: NexusPHP
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH5QQKBykVPLQLsAAABCVJREFUOMuVlctvVVUYxX97n3PPvb0t0BZKSKW0FdpSDCAkViMmjU9kAImaMDVGnOo/4IApGo0xccLQmYkgJhhfCSA4sgUJjz5JsbVwS/q6lN7bc/brc3AanGiiO9mjb+1k7d/KXlvxP9ax04tsfyKmMucatGYrsAysnHln82ON+rfDB967RXU+Zc/hroZSSTeXErVNKfq0Ym8cq6cizQ7rZKyeyYdxxFQ9Fc69u5kYYLxi8Q4aSiq5Mp2VhmZse93SGxS7g7BHK/qiiO44Ui1xRBxppZUC6+TpWMvVjw4WP/n6QeAcoE58s8xCVXZtKKmXTwyUD+/cHHWlTppTK80La7Lxh8ksWloLaKUoFWCwK+HJlhgBRIRI8WtXS3S8oFWlIdHElYWwt6msT0UFdeTStGEpjTnSWySJQIBqKpwfz/AiiFWMzjs2FTWD3QUmFz0/T2StFzxxMcrpxcAhYJ8XmJh3LNQCg90J09VAZ3PEoc4CN+Ys4wsOreBmxZFZ2L8t5uo9y6W7ZkOtJluBPwG0dVzNrCxlRjAOjBVEYHjWMjRr2VLWvNidUECRGcE6wTjBeGGpFgieFgV9CnjliwW0MWHEmjBjTMCagLUCwKO1wPmRlPlVz0BHgYPtMcYEjBXcusYHwXtpEpE9v99ew3tBX3x/S81YGXEu4HzA+wDrwEcrhh/HUwoaXu8t0lZWWJtrRCB4wftACNK/qzPZGIKgj56ex1q5YYxYawRrBRHBeyHNhJ9GUkYfOHraYl7aVUS84JyAgPe52+ClVylpQQT9qBbwPoxZEx46G3A2dxg8eBe4v+w4c61O3QRe6yuye0uMMYIA3gnWBLwLHRJkByLoNBMyIxVj5K5ZZygCzkvOzAhXJte4OJbS2hjxxv4GmhIIQXKNDTgnjc5Jf6wCsXMQhCpaJpSSZx4Dd4I1gkJYyeCroRr7ticMdBWp1sPfmkxQSmIvau9vS41o74VStlZzVkZsFoIxOXDvBJMFjMkxjM4azg7XiDS82l9iY0njbH5lawLehv7u0mqLvn6ynVUSrJMxa+WRMzlw5/OArMl3lga+HV5leCqjIdEkETgnmPW5s7IteGnXkKflvUxYK8utZU0hgnKs8OshORvwLlBZcnx5eYVq3aOUwjtZnwvOyR8SWIwBerYWKBfV7As9xeXne0pdm8qa48810dEa8fn3Ve4vO7TK3+rlkTX57lotvPVsky4X9YzzXItidV0JZ0Pq52KAYwfKbGiMaosP7egvt+sHLt6s5Q6CSGokeE8mmorSTNaMjF0YSWfeHGgqHT3YePnkmepQT2diAZn8uD0v2Ia3p+hrU9xbkcGCklME2kQxh2IyKeibkeIWSk2pSC8prR4iuDufdvxjMT9u7O4PpkGhEXYi0opS0yjmAX/3s87//E38BWXDuj9j0ViVAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIxLTA0LTEwVDA3OjQxOjIxKzAwOjAws0DWvgAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMS0wNC0xMFQwNzo0MToyMSswMDowMMIdbgIAAAAASUVORK5CYII=
asSource: true
asTarget: true
uploadPath: /upload.php
seedDomSelector: '#top~table:first>tbody>tr:nth-child(5)'
torrentDownloadLinkSelector: 'a[href*="download.php?id="]'
search:
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
  result:
    list: '.torrents>tbody>tr'
    url: '.torrentname td a[href*="details.php?id="]'
    name: '.torrentname td a[href*="details.php?id="]'
    size: 'td:nth-child(5)'
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
imdb:
  selector: 'input[name="url"][type="text"]'
douban:
  selector: 'input[name="douban_id"]'
anonymous:
  selector: 'input[name="uplver"]'
torrent:
  selector: '#torrent'
tags:
  chinese_audio: '#tag_gy'
  diy: '#tag_diy'
  cantonese_audio: '#tag_yy'
  chinese_subtitle: '#tag_zz'
  hdr: '#tag_hdr10'
  hdr10_plus: '#tag_hdrm'
  dolby_vision: '#tag_db'
category:
  selector: '#browsecat'
  map:
    movie:
      - '411'
      - '412'
      - '413'
      - '414'
      - '415'
      - '450'
      - '499'
      - '416'
    tv:
      - '425'
      - '426'
      - '471'
      - '427'
      - '428'
      - '429'
      - '430'
      - '452'
      - '431'
    tvPack:
      - '432'
      - '433'
      - '434'
      - '435'
      - '436'
      - '437'
      - '438'
      - '502'
    documentary:
      - '417'
      - '418'
      - '419'
      - '420'
      - '421'
      - '451'
      - '500'
      - '422'
    concert: '441'
    sport:
      - '442'
      - '443'
    cartoon:
      - '444'
      - '445'
      - '446'
      - '447'
      - '448'
      - '454'
      - '449'
      - '501'
    variety: ''
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '1'
    hevc: '12'
    x264: '1'
    x265: '2'
    h265: '2'
    mpeg2: '4'
    mpeg4: '1'
    vc1: '3'
    xvid: '5'
    dvd: '5'
source:
  selector: 'select[name="source_sel"]'
  map:
    uhdbluray: '9'
    bluray: '1'
    hdtv: '4'
    dvd: '3'
    web: '7'
    vhs: '8'
    hddvd: '8'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '6'
    ac3: '15'
    dd: '15'
    dd+: '15'
    dts: '3'
    truehd: '13'
    lpcm: '14'
    dtshdma: '11'
    atmos: '12'
    dtsx: '17'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray:
      - '10'
      - '499'
      - '500'
      - '502'
      - '501'
    bluray:
      - '1'
      - '450'
      - '451'
      - '452'
      - '453'
      - '454'
    remux:
      - '3'
      - '415'
      - '421'
      - '430'
      - '437'
      - '448'
    encode:
      - '7'
      - '411'
      - '412'
      - '413'
      - '414'
      - '416'
      - '417'
      - '418'
      - '419'
      - '420'
      - '422'
      - '425'
      - '426'
      - '471'
      - '427'
      - '428'
      - '429'
      - '431'
      - '432'
      - '433'
      - '434'
      - '435'
      - '436'
      - '438'
      - '444'
      - '445'
      - '446'
      - '447'
      - '449'
    web:
      - '11'
      - '411'
      - '412'
      - '413'
      - '414'
      - '416'
      - '417'
      - '418'
      - '419'
      - '420'
      - '422'
      - '425'
      - '426'
      - '471'
      - '427'
      - '429'
      - '431'
      - '432'
      - '433'
      - '434'
      - '436'
      - '438'
      - '444'
      - '445'
      - '446'
      - '447'
      - '449'
    hdtv:
      - '5'
      - '412'
      - '413'
      - '416'
      - '418'
      - '419'
      - '422'
      - '424'
      - '426'
      - '471'
      - '427'
      - '428'
      - '431'
      - '433'
      - '434'
      - '435'
      - '438'
      - '442'
      - '443'
      - '445'
      - '446'
      - '449'
    dvd:
      - ''
      - '411'
      - '417'
      - '425'
      - '432'
      - '444'
    dvdrip:
      - '7'
      - '411'
      - '417'
      - '425'
      - '432'
      - '444'
    other: ''
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    2160p:
      - '1'
      - '499'
      - '416'
      - '500'
      - '422'
      - '431'
      - '438'
      - '502'
      - '449'
      - '501'
    1080p:
      - '2'
      - '414'
      - '420'
      - '429'
      - '436'
      - '447'
    1080i:
      - '3'
      - '424'
      - '428'
      - '435'
      - '443'
    720p:
      - '4'
      - '413'
      - '419'
      - '423'
      - '427'
      - '434'
      - '442'
      - '446'
    576p:
      - '5'
      - '411'
      - '417'
      - '425'
      - '432'
      - '444'
    480p:
      - '5'
      - '411'
      - '417'
      - '425'
      - '432'
      - '444'
team:
  selector: 'select[name="team_sel"]'
  map:
    hdhome: '1'
    hdh: '2'
    hdhtv: '3'
    hdhpad: '4'
    hdhweb: '12'
    3201: '20'
    shma: '17'
    tvman: '21'
    arin: '19'
    ttg: '6'
    mteam: '7'
    other: '11'
    969154968: '22'
