url: 'http://hdroute.org'
host: hdroute.org
siteType: NexusPHP
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH5QQKBy01Y7bufAAAA3xJREFUOMttlc1vlFUUxn/nzjCoTEsnQClBIehIaNTG+hU0rkwXsNBo4n9QF40kuGFh3GqIC1aYEBKtf4NxA4su1ESNCSHYBBrxI7akQK3tQJwO7cw593Hxvh1a40nu5r3v+b3PPc9z8xpb6oPTpwEMaAIngQnDRkEHAQSLwJzQDOISxm+Azp//rM8wgFPvnwITyBpmvA28Z9gYqC7+t9qSZoEvJL6iohZuXLh4Afvkw49ZWF0gWdpvZmeASWUaGYGs0LWlUgLDyi21QNOIc5Hz0qE9h6jOL88DNMLyGdBUSlYfGa4xOFD5L4v19czyao/2mhdHMxrAlCQQZ+eX51vVzsY6O6s73sGYBOqVZLzx+gAvjg0ibSeudYKFxQ2+/eEec7+uUW7XgUmhuY1e58uUzI56xKR7NNwdj0ASZuWQzfqrvqvKs8d28e6b+zj8eI1ez3F33L0RHpMVakdTRJyI8DEPxz0I974yMyNn0XngbGwEADnD8N4aLzxXxyz3e9x9zCNOVMN9AijcFFQq6SEQaK85X1++A8BbJw6we2AHACPDNVIqgMVAqSNNVD18lBImoBoJKfdD1e1mbi894LFHq2Rps5leL+M93wrEYLTq7gc3hy6Bb1EIkCVee6nBM6NDDA3WkEASN27ep73WLd/tx+tgNTw2BYLAq9rursRAvdI/KsDV2VW++3GJbq+HmRXNpcqqeyyCmpvQqle2AQXkrL6SnMWNX+5xZ6lDsodRLXmLycPnPAKP0q3whzMskXf/6tDtFc8qFeNoc5DaDhUOR7HKyM2lHDETEe3wElrmsH/Zzbg6u8L8rXY/m8eagzz9ZJ2eO+FB2duOiJkUEZfDfTbC+19j2w0Ryysdvvn+Nu4ZCYZ27+SV8b2kJDyKU+XIsxFxOZl0M3JMe0RrU2GWSjdLozz46cpdbi0WKiV4eXyY/ft2FgojWpFjOiVu2qvHjwNqCPtIYipVqB95YoDG0COA6HaD3//8h84Dp3lkkN1ldHIWf8zf5979XtuMi5idBVrWPPAUew7vRZH3C86AJiPU0Bb7UjIMiKxyGsIwUrKWGdMY58zS0vrKCpXVdosDIyNkaQ10RWLB0D6Mhhk1K7MoCQPMwIy2GVdAnwo+t6y/s8TP169vxqeo8efHMcyEmkInzZiQGAU2b9MiMAfMAJeg+AVcu3atz/gXdAVC3vg+5BoAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjEtMDQtMTBUMDc6NDU6NTIrMDA6MDCBhmVAAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIxLTA0LTEwVDA3OjQ1OjUyKzAwOjAw8Nvd/AAAAABJRU5ErkJggg==
asSource: false
asTarget: true
uploadPath: /upload.php
search:
  path: /browse.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  replaceKey: ['tt', '']
  params:
    s: '{name}'
    dp: '0'
    add: '0'
    action: 's'
    or: '4'
    imdb: '{imdb}'
name:
  selector: '#title_eng'
subtitle:
  selector: 'input[name="title_sub"]'
description:
  selector: 'textarea[name="description"]'
poster: 'input[name="poster_big"]'
imdb:
  selector: '#upload-imdb_url'
anonymous:
  selector: 'input[name="is_anonymous"]'
torrent:
  selector: '#file_torrent'
tags:
  chinese_audio: 'input[name="is_mandrain"]'
  cantonese_audio: 'input[name="is_cantonese"]'
  diy: 'input[name="is_diyed"]'
  chinese_subtitle: 'input[name="is_chs_sub_incl"]'
category:
  selector: '#type_category'
  map:
    movie: '1'
    tv: '3'
    tvPack: '3'
    documentary: '2'
    concert: '5'
    sport: '6'
    cartoon: '4'
    variety: '9'
videoCodec:
  selector: '#type_codec'
  map:
    h264: '1'
    hevc: '7'
    x264: '1'
    x265: '7'
    h265: '7'
    mpeg2: '3'
    mpeg4: '1'
    vc1: '2'
    xvid: '4'
    dvd: '3'
audioCodec:
  selector: '#type_audio'
  map:
    aac: '9'
    ac3: '5'
    dd: '5'
    dd+: '5'
    flac: '7'
    dts: '4'
    truehd: '3'
    lpcm: '1'
    dtshdma: '2'
    atmos: '2'
    dtsx: '4'
videoType:
  selector: '#type_medium'
  map:
    uhdbluray: '1'
    bluray: '1'
    remux: '2'
    encode: '4'
    web: '6'
    hddvd: '6'
    hdtv: '3'
    dvd: '6'
    dvdrip: '6'
    other: '6'
resolution:
  selector: '#type_resolution'
  map:
    2160p: '7'
    1080p: '1'
    1080i: '2'
    720p: '4'
    576p: '6'
    480p: '6'
