url: 'https://pt.keepfrds.com'
host: keepfrds.com
siteType: NexusPHP
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAACDVBMVEX////8/Pz19fXs7Oz09PT+/v7p6enQ0NC7u7uwsLCvr6+6urrOzs7n5+f7+/v6+vri4uKrq6uBgYFzc3N5eXl6enp0dHR/f3+np6be3t75+fjj4+OSkpJ8fHyhoaHh4eHT09OlpaV+fn2Li4ve3t3s8PXu8vfh5uu6vsKLjY+3uLjl5eX5+fm8vLyLjY6zt7vf4+isvtSOp8WCnsB+mbl6kKyutb3c3d7v7u7m5ubY2NjY2NfP0NGqsrt1jKd8lreCnr+OqMWcss1chLAvZZ4uZp9ahbPS3ejOzs+3trbLy8ugoKCioqHBwsPK1eJXg7EtZZ8uZJ5bhLCds83t8faoxt9Yl8g/icJ2qtLh6vGwr697e3uNjY3FxcWRkZGenp3MzMvf6fFyqNE8h8FXlseoxd78/f7f7PWPweJWpdZ7uuDh7fWzs7OampqoqKipqamXl5enp6fk8fh4uN9Uo9X6/P3Q6PaQzex3xenX7ffP0dLR0NDW1ta5ubna2trx8fH1+PnY8Pp0xOqOzOz1/P/L5vKUwtaxwMfa3N329fX39/f4+Pjq7e6xwsmOvtLJ5fD2/P/x8/PDyMuMjpC0tLX29va2t7eKjo67wcPu8PH9/P3m5eWXlpabm5vKysrd3d3MzMyQkI/h4OCxsbGGhoZ4eHiEhISurq79/f3U1NTAwMC1tbW/v7/q6urw8PAgqDn/AAAAAWJLR0QAiAUdSAAAAAd0SU1FB+UECgYrK84hHq4AAAEbSURBVBjTY2AgFTAyMTOzMCKLsDKysXNwcnHz8PKxwgX5BQSFhEVExcQlJKXAoqysDIzSMrJy7PICCopKyir8IBFVVTV1DU0tbR1WVj42XT19AzVVVQZDI2MTUzNzC2ZLeStrG1s7ewdHQwYnZxdXN3cPTw4vbm8fXz//gMCgYIaQ0LDwiMio6JhYwbj4hMSk5JTUEIa09IzMrOyc3Lz8gsJY7aLikoz0NAbW0rLyisqq6hqO2rr6hsam5rJSkKtaWtvaOzq7tHm7GXp6+/onQNw+cdLkKfJTWVm7pKdNnzET6qFZs+dEz503f/4Cb9mFi/jg3tRevERs6VKxZcsFdOCeZ13BvHLV6tVrFNYysqIEVHf9uu4VJIc4AFHVRtljPRexAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIxLTA0LTEwVDA2OjQzOjQzKzAwOjAwO9PHqAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMS0wNC0xMFQwNjo0Mzo0MyswMDowMEqOfxQAAAAASUVORK5CYII=
asSource: true
asTarget: true
seedDomSelector: '#top~table:first>tbody>tr:nth-child(3)'
torrentDownloadLinkSelector: 'a[href*="download.php?id="]'
uploadPath: /upload.php
needDoubanInfo: true
search:
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: 'input[name="small_descr"]'
subtitle:
  selector: '#name'
description:
  selector: '#descr'
imdb:
  selector: 'input[name="url"][type="text"]'
douban:
  selector: 'input[name="douban_url"]'
anonymous:
  selector: 'input[name="uplver"]'
torrent:
  selector: 'input[name="file"]'
category:
  selector: '#browsecat'
  map:
    movie: '401'
    tv: '402'
    tvPack: '402'
    documentary: '404'
    concert: '408'
    sport: '407'
    cartoon: '405'
    variety: '403'
source:
  selector: 'select[name="source_sel"]'
  map:
    uhdbluray: '10'
    bluray: '1'
    hdtv: '4'
    dvd: '3'
    web: '7'
    vhs: '8'
    hddvd: '8'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '3'
    hevc: '0'
    x264: '3'
    x265: '0'
    h265: '0'
    mpeg2: '17'
    mpeg4: '1'
    vc1: '16'
    xvid: '5'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    4320p: '0'
    2160p: '7'
    1080p: '1'
    1080i: '2'
    720p: '3'
    576p: '5'
    480p: '5'
