url: 'https://ourbits.club'
host: ourbits.club
siteType: NexusPHP
icon: '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="11px" height="11px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">  <image id="image0" width="20" height="20" x="0" y="0"    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAAB3RJTUUH5QQKBicSPZHZqgAABUJJREFUOMsFwdlvXFcBB+Dfuefcc7eZ8awZ22M7jpfGxQlZGpoWhxYVgVpaqQuPSMATz/wFiH+BRx4QQkgVCAkQS1GRQIgi5BIVxwlJG+yOxxnbs8+9c5e567mH7yMAwA57+HHtO3jf/56yIHUz0262JPS7Rna0d4m3b+qG1joOr9HzXtlJnOSJTtJ/GWb+b1UMPhV91W5u/FR8fvgTPPy+DvZhcBlNcw2n3i5Zu/hLcyKuf2VCF782L67tLKpRc2W2X5XdkTVJYkzkK7qmE6OqnqwuqZ2XeBr+A0vZByHNTzZfeSHfOPwmWJAu4DwwSZDwK63gozdGY+c9p/rinbReKgmzjJltwu3nsDUus6ppcE2UNeFfbrFHX1ytHW2PM9Z84jR+nTjPP1JAc/YBPVQa/ofNS8GPXick/C4R3nUiZpqRnkFkGp5pb2LWdMHKN0i5UAFPRjAdB5XkMa/jwW7PqVaCfkWd5D/4+Yzu/Y8VaM9SzeReNNfeg0GuWQ1LW8M+iY/vY67fRty4B3rFQKGoQmYZtOEzMPcYPS8l7qTAuq5YhkzfXV74r7ubDX7GcnGxYmmdN1SDvWhSV6+Ih0R1ztAdX4VvrEMhM6jMQJoJZPMh6MUBnN4znAVbmGMXBRN0uzFcb1m/3IuHO49ZlvC7SJ4+5533iheHIYZuiGHxGvr1t5DxDViRi+g0RzhXQdFFiQ9gVAWCwjpCbGO1OSOtQkdV7aPtc4+8zWahvOcnnUY0foZ+bwEd7w5GxXcQNm9D0QTg+eBOAuoF+MLSU6zXn4CSNrbpDIl5ARn68IYjzM4WGt1B4WXW9vhNNTRqXKkgXLkD33sbQt8CoQGkEkEIDQqKaDTGuHX5AZpkH6E7Qb1yCmpJfNzJ8eTxMqajXcO215rsNCqukujLZsW6hGhnD2rwVah2gjycgUdAwSbQcgqjocGNAiTjGFSUUFooIrYD+F4ATxTlJN1SbH9LZyCMjArvkISPoFOKMgMyX4OcFGAmMcwwB+EBfK+AT7xXwWYENcNG5rkwlEOUCjFqNYlR2oAkt8DKIekn5jJz5KK+JNu4av4dTd3D0/YaXOcKJFehFQIIksG3vgSfXIdDp1gr7GPdOIY9tDHzFgjYUl5arkTMdJJHwWhsRTArS6UhWuXfoqF2kJlb6MUvIZbPIZ6XkDICSUsI4mXwvAIxP4BZlshzAtctIRKl0KxlQybt2T+D7mAjEcUNuzFFvxWiwU9xc+cEm/FnOO6/iqPpmwjVZdA4gzzvQsRH8LQD2FaIWFxCltaQhmLCzfl9uvKNb2Vur7uTurNN3+eqm9RJURtha6WPgtHDwDUwEC9DFK8AaYjos2OQ9n2U2CFyjaDd38PF8JaQqXbQoORXzGSyUy+Zfx10zjfdXvn2mbOtlcUNlPUT+HaC9lEFc90E1+YQng3pDzB3HDx+WMbx8Cps7fU8x+KgqIw/QRrss9rqmiuC5G8JoYt5Jip+f75xShdVQymT2NYwOGkhLPpQlD6QJVBLFuLSIvq2IWWyKEldcwwr/TM32O+zrRsuLVdfkMTxPV01JllG0iTJqqHgVUkjFiY1uLN1RK4ic38KmWWQqgZBOBEZF4pqnjI1/QPB9BfFev2BtnlLoRt334WRSik5m2RK0s2helHCY1Ae5aQm0qRIMjck+eQil6Ebg5CpwmiHUvkfXRV/5DJ6P7O7B823vp0CXNLTj3+H2tdfgx/o0ipnbjietRG4nyOz5nle4cipriQ+V0JbKMHUURPvyKLyo5Kp/4Zz+ifEfmf62g/T1vNcSg/i/8nGx5VMcAmaAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIxLTA0LTEwVDA2OjM5OjE4KzAwOjAwTy0YfAAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMS0wNC0xMFQwNjozOToxOCswMDowMD5woMAAAAAASUVORK5CYII=" /></svg>'
asSource: true
asTarget: true
seedDomSelector: '#top~table:first>tbody>tr:nth-child(3)' 
uploadPath: /upload.php
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
  result: 
    list: '#torrenttable>tbody>tr'
    url: '.torrentname td a[href*="details.php?id="]'
    name: '.torrentname td a[href*="details.php?id="]'
    size: 'td:nth-child(5)'
name:
  selector: 'input[name="name"]'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
poster: 'input[name="picture"]'
imdb:
  selector:  'input[name="url"][type="text"]'
anonymous: 
  selector: 'input[name="uplver"]'
tags: 
  chinese_audio: '#tagGY'
  diy: '#tagDIY'
  cantonese_audio: '#tag_yy'
  chinese_subtitle: '#tagZZ'
  hdr: '#tagHDR10'
  hdr10_plus: '#tagHDR10P'
  dolby_vision: '#tagDB'
category:
  selector: 'select[name="type"]'
  map:
    movie: '401'
    3d: '402'
    tv: '412'
    tvPack: '405'
    documentary: '410'
    concert: '419'
    sport: '415'
    cartoon: '411'
    variety: '413'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '12'
    hevc: '14'
    x264: '12'
    x265: '14'
    h265: '14'
    mpeg2: '15'
    mpeg4: '12'
    vc1: '16'
    xvid: '17'
    dvd: '18'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '7'
    ac3: '6'
    dd: '6'
    dd+: '6'
    flac: '13'
    dts: '4'
    truehd: '2'
    lpcm: '5'
    dtshdma: '1'
    atmos: '14'
    dtsx: '21'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '12'
    bluray: '1'
    remux: '4'
    encode: '7'
    web: '9'
    hdtv: '5'
    dvd: '2'
    dvdrip: '2'
    other: '0'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    2160p: '5'
    1080p: '1'
    1080i: '2'
    720p: '3'
    576p: '4'
    480p: '4'
area:
  selector: 'select[name="processing_sel"]'
  map:
    CN: '1'
    US: '2'
    EU: '2'
    HK: '3'
    TW: '3'
    JP: '4'
    KR: '5'
    OT: '6'