url: https://www.pthome.net
host: pthome.net
siteType: NexusPHP
icon: '<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="11px" height="11px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">  <image id="image0" width="20" height="20" x="0" y="0"    href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAABR1BMVEUAAAD/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/sxz/shv/shv/sxz/sxz/sxz/sxz/sxv/sxz/shv/shr/sx3/tB//vj7/zWv/2pH/4ab/zmz/vTz/2Y7/7s7/+e7//v3/////sx7/uS7/ujH/x1j/68T/8dX/1YL/03z/25P/zGj/6b7/7Mj/9OD//fn/shn/033/sxv/w07/8tj/1oX/1oT/vj//uCr/463//v7/893/14r/14j/8db/2Iv/vDn/57n/+vD///7//fv//fr/6b3/vDj/vTv/ymD/35//89z/xE//yV//6Lv/7MX/7Mf/uTD/0nj/+vH/7sz/1YH/3Zr/uC3/x1r/+e3/5bL/yV3/9N3/8NP/yWD/ujP/zm7/xFD/57j/4qr/wkn/vDf/tym6/awGAAAAGHRSTlMAAAEmcLXj+bYPYsPx/hWL7u6LEPTi+u42ThkjAAAAAWJLR0QnLQ+oIwAAAAd0SU1FB+UECgYoFFNqYFAAAAE4SURBVBjTZdFXW8IwFAbgpINKW1pGq0laFRSIC5xUxIkDFTfiwL33/7/2pMUrz+X7nDz58gUhhLAkK2pM02I9iixhJAbjuG6YCQKTMA09jrEwy06SaCilqbQFijO20xXGPN9z0hmMJD3ao8zvHxjM5ryULiHZCIXRoeF8ocizPjVkpJhgI6Nj4xOl8mSpOOVRU0GqsOmZ2blKmQbzhRyjREUuqbKFGue8skjIUn6ZEeKiXsJWVtcAeX19Y3PLp4RogEFju74DuNvc2z9gIbqE+odHx02xe9ISBsdVQslpu3xWATy/YCKyCpGod9m5ur7pcN6+FQiRIDy7q90/PD7x5xdPnIbwkt5HX1tv742Pz6/QkvBMUQgL4Lbvn/AWx4ZCouqgtIBVxZ5tRYX+L/nvO1xNc9Xud/wCUFAuZX3Re8sAAAAldEVYdGRhdGU6Y3JlYXRlADIwMjEtMDQtMTBUMDY6NDA6MjArMDA6MDAnY2+xAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIxLTA0LTEwVDA2OjQwOjIwKzAwOjAwVj7XDQAAAABJRU5ErkJggg==" /></svg>'
asSource: true
asTarget: true
uploadPath: /upload.php
seedDomSelector: '#top~table:first>tbody>tr:nth-child(3)' 
search: 
  path: /torrents.php
  imdbOptionKey: '4'
  nameOptionKey: '0'
  params:
    incldead: '0'
    search_area: '{optionKey}'
    search: '{imdb}'
    sort: '5'
    type: desc
name:
  selector: '#name'
subtitle:
  selector: 'input[name="small_descr"]'
description:
  selector: '#descr'
imdb:
  selector: 'input[name="url"][type="text"]'
douban:
  selector: 'input[name="douban_id"]'
anonymous: 
  selector: 'input[name="uplver"]'
tags: 
  chineseAudio: '#tag_gy'
  DIY: '#tag_diy'
  cantoneseAudio: '#tag_yy'
  chineseSubtitle: '#tag_zz'
  HDR: '#tag_hdr10'
  HDR10+: '#tag_hdrm'
  DolbyVision: '#tag_db'
category:
  selector: '#browsecat'
  map:
    movie: '401'
    tv: '402'
    tvPack: '402'
    documentary: '404'
    concert: '408'
    sport: '407'
    cartoon: '405'
    variety: '403'
videoCodec:
  selector: 'select[name="codec_sel"]'
  map:
    h264: '1'
    x264: '1'
    hevc: '6'
    x265: '6'
    h265: '6'
    mpeg2: '4'
    mpeg4: '1'
    vc1: '2'
    xvid: '5'
    dvd: '4'
audioCodec:
  selector: 'select[name="audiocodec_sel"]'
  map:
    aac: '6'
    ac3: '18'
    dd: '18'
    dd+: '18'
    flac: '1'
    dts: '3'
    truehd: '20'
    lpcm: '21'
    dtshdma: '19'
    atmos: '19'
    dtsx: '3'
videoType:
  selector: 'select[name="medium_sel"]'
  map:
    uhdbluray: '12'
    bluray: '1'
    remux: '3'
    encode: '15'
    web: '10'
    hdtv: '5'
    dvd: '2'
    dvdrip: '15'
    other: '11'
resolution:
  selector: 'select[name="standard_sel"]'
  map:
    4320p: '10'
    2160p: '5'
    1080p: '1'
    1080i: '2'
    720p: '3'
    576p: '4'
    480p: '4'
team: 
  selector: 'select[name="team_sel"]'
  map:
    pthome: '19'
    pth: '21'
    pthweb: '20'
    pthtv: '22'
    pthaudio: '23'
    pthebook: '24'
    pthmusic: '25'
    other: '5'